name: Continuos Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
      output-directory: ./output
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          working-directory: ${{env.working-directory}}
          bundler-cache: true

      - name: Setup Asciidoctor, Graphviz and Pandoc
        run: |
          sudo apt-get install graphviz pandoc --no-install-recommends
          bundle exec asciidoctor --version

      - name: Generate HTML document
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -D $GITHUB_WORKSPACE/${{env.output-directory}}/html *.adoc

      - name: Generate PDF document
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -r asciidoctor-pdf -b pdf -D $GITHUB_WORKSPACE/${{env.output-directory}}/pdf *.adoc

      - name: Generate MS Word document
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -b docbook -D $GITHUB_WORKSPACE/${{env.output-directory}}/word *.adoc
          cd $GITHUB_WORKSPACE/${{env.output-directory}}/word
          for f in *.xml; do pandoc --from docbook --to docx "$f" -s -o "${f%.xml}.docx"; done

      - name: Publish HTML document artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-html
          path: ${{env.output-directory}}/html
          if-no-files-found: error

      - name: Publish PDF document artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdf
          path: ${{env.output-directory}}/pdf
          if-no-files-found: error

      - name: Publish MS Word document artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-word
          path: ${{env.output-directory}}/word/**/*.docx
          if-no-files-found: error

      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{env.output-directory}}/html
          commit_message: ${{ github.event.head_commit.message }}
