name: Continuos Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
      output-directory: ./output

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          working-directory: ${{env.working-directory}}
          bundler-cache: true

      - name: Install Asciidoctor
        run: |
          bundle exec asciidoctor --version
        working-directory: ${{env.working-directory}}

      - name: Setup Graphviz
        run: |
          sudo apt-get install graphviz

      - name: Generate HTML document
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -D $GITHUB_WORKSPACE/${{env.output-directory}}/html *.adoc
        working-directory: ${{env.working-directory}}

      - name: Generate PDF document
        run: |
          bundle exec asciidoctor -r asciidoctor-pdf -r asciidoctor-diagram -b pdf -D $GITHUB_WORKSPACE/${{env.output-directory}}/pdf *.adoc
        working-directory: ${{env.working-directory}}

      - name: Publish HTML document artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-html
          path: ${{env.output-directory}}/html
          if-no-files-found: error

      - name: Publish PDF document artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdf
          path: ${{env.output-directory}}/pdf
          if-no-files-found: error
