name: Continuos Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          working-directory: src
          bundler-cache: true

      - name: Install Asciidoctor
        run: |
          bundle exec asciidoctor --version
        working-directory: src

      - name: Setup Graphviz
        run: |
          sudo apt-cache install graphviz
      
      - name: Generate HTML document
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -D ../output *.adoc
        working-directory: src

      - name: Publish HTML document artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: output
