name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - doc/**
  pull_request:
    branches:
      - main
    paths:
      - doc/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./doc
      output-directory: ./output
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          working-directory: ${{env.working-directory}}
          bundler-cache: true

      - name: Setup Asciidoctor, Graphviz and Pandoc
        run: |
          sudo apt-get install graphviz pandoc --no-install-recommends
          bundle exec asciidoctor --version
        working-directory: ${{env.working-directory}}

      - name: Generate HTML documents
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -D $GITHUB_WORKSPACE/${{env.output-directory}}/html *.adoc
        working-directory: ${{env.working-directory}}

      - name: Generate PDF documents
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -r asciidoctor-pdf -b pdf -D $GITHUB_WORKSPACE/${{env.output-directory}}/pdf *.adoc
        working-directory: ${{env.working-directory}}

      - name: Generate Markdown documents
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -b docbook -D $GITHUB_WORKSPACE/${{env.output-directory}}/markdown *.adoc
          cd $GITHUB_WORKSPACE/${{env.output-directory}}/markdown
          for f in *.xml; do pandoc --from docbook --to gfm --wrap=none "$f" -s -o "${f%.xml}.md"; done
        working-directory: ${{env.working-directory}}

      - name: Generate MS Word documents
        run: |
          bundle exec asciidoctor -r asciidoctor-diagram -b docbook -D $GITHUB_WORKSPACE/${{env.output-directory}}/word *.adoc
          cd $GITHUB_WORKSPACE/${{env.output-directory}}/word
          for f in *.xml; do pandoc --from docbook --to docx "$f" -s -o "${f%.xml}.docx"; done
        working-directory: ${{env.working-directory}}

      - name: Publish HTML documents artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-html
          path: ${{env.output-directory}}/html
          if-no-files-found: error

      - name: Publish PDF documents artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdf
          path: ${{env.output-directory}}/pdf
          if-no-files-found: error

      - name: Publish MS Word documents artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-word
          path: ${{env.output-directory}}/word/**/*.docx
          if-no-files-found: error

      - name: Publish to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{env.output-directory}}/html
          commit_message: ${{ github.event.head_commit.message }}

      - name: Checkout Wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki

      - name: Push to Wiki
        run: |
          cd ${{env.output-directory}}/markdown
          cp **/*.md ../../wiki
          cp **/*.svg ../../wiki
          cd ../../wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add changes" && git push
